name: Push rjio-fetch to Dockerhub

on:
  push:
    branches: 
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build -t rjio-fetch -f docker/Dockerfile-rjio-fetch .
      - name: Publish to Dockerhub 
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wiennat/rjio-fetch
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
