name: "Tagged-release"

on:
  push:
    tags:
      - "rjio-fetch/v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'
      - name: Prepare deps
        run: make deps
      - name: Build go binary
        run: make build-fetch
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            dist/*